<?php

namespace App\Services;

use App\Models\OwnerAccount;
use App\Models\OwnerTransaction;
use App\Models\User;
use App\Services\Accounting\OwnerFinancialJournalService;
use Illuminate\Support\Facades\DB;
use RuntimeException;

/**
 * Handles direct owner-ledger operations that are not generated by
 * tenant payments, expenses, fees or payouts.
 *
 * Patrimoine uses this service for:
 * - owner deposits;
 * - manual positive adjustments;
 * - manual negative adjustments.
 *
 * All owner balances remain derived from OwnerTransaction records.
 */
class OwnerLedgerService
{
    public function __construct(
        private readonly OwnerFinancialJournalService $journal
    ) {
    }

    /**
     * Record actual money received from an owner.
     *
     * The deposit increases the owner's consolidated balance. Building and Unit
     * references provide operational context but do not create or settle an
     * expense automatically.
     */
    public function recordDeposit(
        OwnerAccount $account,
        int $amount,
        string $transactionDate,
        string $paymentMethod,
        string $depositPurpose,
        ?int $buildingId = null,
        ?int $unitId = null,
        ?string $reference = null,
        ?User $cashReceiverUser = null,
        ?string $notes = null
    ): OwnerTransaction {
        if ($amount <= 0) {
            throw new RuntimeException(
                __('business.owner.deposit_positive')
            );
        }

        if (
            ! in_array(
                $paymentMethod,
                [
                    'cash',
                    'bank_transfer',
                    'momo',
                ],
                true
            )
        ) {
            throw new RuntimeException(
                __('business.owner.deposit_payment_method')
            );
        }

        if (
            ! in_array(
                $depositPurpose,
                [
                    'general_funding',
                    'property_expense',
                    'repair_maintenance',
                    'other',
                ],
                true
            )
        ) {
            throw new RuntimeException(
                __('business.owner.deposit_purpose')
            );
        }

        if (
            $paymentMethod === 'cash'
            && $cashReceiverUser === null
        ) {
            throw new RuntimeException(
                __('business.owner.cash_collector_required')
            );
        }

        return DB::transaction(
            function () use (
                $account,
                $amount,
                $transactionDate,
                $paymentMethod,
                $depositPurpose,
                $buildingId,
                $unitId,
                $reference,
                $cashReceiverUser,
                $notes
            ): OwnerTransaction {
                $account = OwnerAccount::query()
                    ->lockForUpdate()
                    ->findOrFail($account->id);

                $transaction = OwnerTransaction::create([
                    'owner_account_id' => $account->id,

                    'building_id' => $buildingId,

                    'unit_id' => $unitId,

                    'direction' => 'credit',

                    'category' => 'owner_deposit',

                    'amount' => $amount,

                    'transaction_date' => $transactionDate,

                    'payment_method' => $paymentMethod,

                    'deposit_purpose' => $depositPurpose,

                    /*
                     * V1.0.5:
                     * Cash Receiver is the authenticated User.
                     * Preserve both relationship and frozen name snapshot.
                     * Non-cash transactions have no Cash Receiver.
                     *
                     * collector_name remains a legacy historical column and
                     * is intentionally not populated by new transactions.
                     */
                    'cash_receiver_user_id' => (
                        $paymentMethod === 'cash'
                            ? $cashReceiverUser?->id
                            : null
                    ),

                    'cash_receiver_name' => (
                        $paymentMethod === 'cash'
                            ? $cashReceiverUser?->name
                            : null
                    ),

                    'reference' => $reference,

                    'notes' => $notes
                        ?? 'Funds deposited by owner.',
                ]);

                /*
                 * Operational Owner ledger + Financial Journal are one
                 * transaction. Before cutover this is intentionally a no-op.
                 */
                $this->journal->postDeposit(
                    $transaction
                );

                return $transaction;
            }
        );
    }

    /**
     * Record a manual owner-ledger adjustment.
     *
     * Adjustments are intended for exceptional administrative corrections.
     * Normal business activity should use the dedicated services for
     * payments, expenses, fees, commissions and payouts.
     *
     * Positive adjustments increase the owner balance.
     * Negative adjustments reduce the owner balance.
     */
    public function recordAdjustment(
        OwnerAccount $account,
        string $direction,
        int $amount,
        string $transactionDate,
        string $reason,
        ?string $reference = null
    ): OwnerTransaction {
        if (! in_array($direction, ['credit', 'debit'], true)) {
            throw new RuntimeException(
                __('business.owner.adjustment_direction')
            );
        }

        if ($amount <= 0) {
            throw new RuntimeException(
                __('business.owner.adjustment_positive')
            );
        }

        $reason = trim($reason);

        if ($reason === '') {
            throw new RuntimeException(
                __('business.owner.adjustment_reason')
            );
        }

        return DB::transaction(function () use (
            $account,
            $direction,
            $amount,
            $transactionDate,
            $reason,
            $reference
        ): OwnerTransaction {
            $account = OwnerAccount::query()
                ->lockForUpdate()
                ->findOrFail($account->id);

            return OwnerTransaction::create([
                'owner_account_id' => $account->id,
                'direction' => $direction,
                'category' => 'adjustment',
                'amount' => $amount,
                'transaction_date' => $transactionDate,
                'reference' => $reference,
                'notes' => $reason,
            ]);
        });
    }
}
