<?php

namespace App\Services;

use App\Models\OwnerAccount;
use App\Models\OwnerTransaction;
use Illuminate\Support\Facades\DB;
use RuntimeException;

/**
 * Handles direct owner-ledger operations that are not generated by
 * tenant payments, expenses, fees or payouts.
 *
 * Patrimoine uses this service for:
 * - owner deposits;
 * - manual positive adjustments;
 * - manual negative adjustments.
 *
 * All owner balances remain derived from OwnerTransaction records.
 */
class OwnerLedgerService
{
    /**
     * Record money deposited by an owner into Patrimoine.
     *
     * Owner deposits increase the owner's available balance and may be used
     * to offset a previously negative balance caused by expenses or fees.
     */
    public function recordDeposit(
        OwnerAccount $account,
        int $amount,
        string $transactionDate,
        ?string $reference = null,
        ?string $notes = null
    ): OwnerTransaction {
        if ($amount <= 0) {
            throw new RuntimeException(
                'Owner deposit amount must be greater than zero.'
            );
        }

        return DB::transaction(function () use (
            $account,
            $amount,
            $transactionDate,
            $reference,
            $notes
        ): OwnerTransaction {
            $account = OwnerAccount::query()
                ->lockForUpdate()
                ->findOrFail($account->id);

            return OwnerTransaction::create([
                'owner_account_id' => $account->id,
                'direction' => 'credit',
                'category' => 'owner_deposit',
                'amount' => $amount,
                'transaction_date' => $transactionDate,
                'reference' => $reference,
                'notes' => $notes ?? 'Funds deposited by owner.',
            ]);
        });
    }

    /**
     * Record a manual owner-ledger adjustment.
     *
     * Adjustments are intended for exceptional administrative corrections.
     * Normal business activity should use the dedicated services for
     * payments, expenses, fees, commissions and payouts.
     *
     * Positive adjustments increase the owner balance.
     * Negative adjustments reduce the owner balance.
     */
    public function recordAdjustment(
        OwnerAccount $account,
        string $direction,
        int $amount,
        string $transactionDate,
        string $reason,
        ?string $reference = null
    ): OwnerTransaction {
        if (! in_array($direction, ['credit', 'debit'], true)) {
            throw new RuntimeException(
                'Owner adjustment direction must be credit or debit.'
            );
        }

        if ($amount <= 0) {
            throw new RuntimeException(
                'Owner adjustment amount must be greater than zero.'
            );
        }

        $reason = trim($reason);

        if ($reason === '') {
            throw new RuntimeException(
                'Owner adjustment reason is required.'
            );
        }

        return DB::transaction(function () use (
            $account,
            $direction,
            $amount,
            $transactionDate,
            $reason,
            $reference
        ): OwnerTransaction {
            $account = OwnerAccount::query()
                ->lockForUpdate()
                ->findOrFail($account->id);

            return OwnerTransaction::create([
                'owner_account_id' => $account->id,
                'direction' => $direction,
                'category' => 'adjustment',
                'amount' => $amount,
                'transaction_date' => $transactionDate,
                'reference' => $reference,
                'notes' => $reason,
            ]);
        });
    }
}
