<?php

return [
    'export_title' => 'Activity Log',
    'no_export_records' => 'No Activity Log records match the selected filters.',
    'export_read_only_notice' => 'This export is a read-only historical record of meaningful human actions recorded by Patrimoine.',
    /*
    |--------------------------------------------------------------------------
    | Activity Log Export Presentation
    |--------------------------------------------------------------------------
    |
    | These translations are used by server-generated Activity Log exports.
    |
    | Internal action identifiers, entity types, role values and database
    | field names remain stable application values. Translation applies only
    | when those values are presented to a human in PDF/CSV output.
    |
    */

    'title' => 'Activity Log',
    'subtitle' => 'Human Action Audit Trail',
    'description' => 'Immutable historical record of meaningful human actions recorded by Patrimoine.',

    'property_management' => 'Property Management',

    'generated_at' => 'Generated At',
    'generated_by' => 'Generated By',
    'generated_by_patrimoine_for' => 'Generated by Patrimoine for',
    'this_installation' => 'this installation',

    'filters' => 'Filters',
    'all_records' => 'All Activity Log records',
    'no_filters' => 'No filters applied',
    'from' => 'From',
    'to' => 'To',
    'user' => 'User',
    'role' => 'Role',
    'action' => 'Action',
    'record_type' => 'Record Type',
    'search' => 'Search',

    'no_records' => 'No Activity Log records matched the selected criteria.',

    /*
    |--------------------------------------------------------------------------
    | Export Columns
    |--------------------------------------------------------------------------
    */

    'columns' => [
        'id' => 'Event ID',
        'timestamp' => 'Timestamp',
        'actor_name' => 'Actor',
        'actor_email' => 'Actor Email',
        'actor_role' => 'Role',
        'action' => 'Action',
        'entity_type' => 'Record Type',
        'entity_id' => 'Record ID',
        'entity_label' => 'Record',
        'ip_address' => 'IP Address',
        'before_values' => 'Before Values',
        'after_values' => 'After Values',
        'snapshot' => 'Snapshot',
        'metadata' => 'Metadata',
    ],

    /*
    |--------------------------------------------------------------------------
    | Detail / Structured Historical Context
    |--------------------------------------------------------------------------
    */

    'event' => 'Event',
    'actor' => 'Actor',
    'entity' => 'Record',
    'before_values' => 'Before Values',
    'after_values' => 'After Values',
    'snapshot' => 'Snapshot',
    'metadata' => 'Metadata',
    'not_available' => 'Not available',
    'unknown_actor' => 'Unknown actor',
    'yes' => 'Yes',
    'no' => 'No',

    /*
    |--------------------------------------------------------------------------
    | Roles
    |--------------------------------------------------------------------------
    */

    'roles' => [
        'administrator' => 'Administrator',
        'property_manager' => 'Property Manager',
        'viewer' => 'Viewer',
    ],

    /*
    |--------------------------------------------------------------------------
    | Activity Actions
    |--------------------------------------------------------------------------
    |
    | Known V1.0.3 human-action identifiers receive explicit labels.
    |
    | The export formatter added in R7 will retain a safe humanized fallback
    | for any future action identifier that does not yet have a translation.
    |
    */

    'actions' => [

        /* ---- V1.0.35: actions that were written but never named ---- */
        'adjustment_voucher.downloaded' => 'Adjustment Voucher Downloaded',
        'auth.email_verified' => 'E-mail Address Verified',
        'auth.invitation_accepted' => 'Invitation Accepted',
        'auth.password_changed' => 'Password Changed',
        'auth.password_reset' => 'Password Reset',
        'expense_invoice.created' => 'Tenant Expense Invoice Created',
        'invoice_account_payment.cancelled' => 'Invoice Payment From Account Cancelled',
        'invoice_account_payment.recorded' => 'Invoice Paid From Account',
        'invoice_payment_receipt.downloaded' => 'Invoice Payment Receipt Downloaded',
        'lease.extended' => 'Lease Extended',
        'lease.rent_increment_cancelled' => 'Rent Increase Cancelled',
        'lease.rent_increment_scheduled' => 'Rent Increase Scheduled',
        'lease.termination_cancelled' => 'Lease Termination Cancelled',
        'lease.termination_completed' => 'Lease Termination Completed',
        'lease.termination_initiated' => 'Lease Termination Started',
        'lease.termination_notice_downloaded' => 'Termination Notice Downloaded',
        'organisation.closed_by_customer' => 'Account Closed By Customer',
        'organisation.data_exported' => 'Organisation Data Exported',
        'organisation.registered' => 'Organisation Registered',
        'owner_expense_bill.downloaded' => 'Expense Bill Downloaded',
        'owner_expense_bill.recorded' => 'Expense Bill Recorded',
        'owner_expense_bill.resent' => 'Expense Bill Resent',
        'owner_expense_bill_payment.cancelled' => 'Expense Bill Payment Cancelled',
        'owner_expense_bill_payment.recorded' => 'Expense Bill Paid',
        'owner_expense_bill_payment_receipt.downloaded' => 'Expense Bill Payment Receipt Downloaded',
        'owner_payout_receipt.downloaded' => 'Owner Payout Receipt Downloaded',
        'owner_reserve_transfer.recorded' => 'Transfer Between Owner Accounts',
        'owner_reserve_transfer_voucher.downloaded' => 'Owner Transfer Voucher Downloaded',
        'owner_reserve_transfer_voucher.resent' => 'Owner Transfer Voucher Resent',
        'party.data_exported' => 'Party Data Exported',
        'party.erased' => 'Party Erased',
        'registry.exported' => 'Registry Exported',
        'registry.imported' => 'Registry Imported',
        'security_deposit.deduction_added' => 'Security Deposit Deduction Added',
        'tenant_adjustment.recorded' => 'Tenant Balance Adjusted',
        'tenant_expense.recorded' => 'Tenant Expense Recorded',
        'tenant_expense_voucher.downloaded' => 'Tenant Expense Voucher Downloaded',
        'tenant_expense_voucher.resent' => 'Tenant Expense Voucher Resent',
        'tenant_fund.deposit' => 'Tenant Fund Deposit',
        'tenant_fund.transfer_recorded' => 'Transfer Between Tenant Accounts',
        'tenant_fund_transfer_voucher.downloaded' => 'Tenant Transfer Voucher Downloaded',
        'tenant_fund_transfer_voucher.resent' => 'Tenant Transfer Voucher Resent',
        'tenant_withdrawal.recorded' => 'Tenant Withdrawal Recorded',
        'auth.login' => 'Signed In',
        'auth.login_failed' => 'Sign-In Failed',
        'auth.logout' => 'Signed Out',
        'auth.device_revoked' => 'Device Signed Out',
        'auth.devices_revoked' => 'Other Devices Signed Out',

        'user.created' => 'User Created',
        'user.updated' => 'User Updated',
        'user.deleted' => 'User Deleted',
        'user.invitation_resent' => 'User Invitation Resent',
        'user.password_reset_requested' => 'User Password Reset Requested',
        'user.invitation_accepted' => 'User Invitation Accepted',
        'user.password_reset' => 'Password Reset Completed',
        'user.password_changed' => 'Password Changed',

        'party.created' => 'Party Created',
        'party.updated' => 'Party Updated',
        'party.deleted' => 'Party Deleted',

        'building.created' => 'Building Created',
        'building.updated' => 'Building Updated',
        'building.deleted' => 'Building Deleted',

        'unit.created' => 'Unit Created',
        'unit.updated' => 'Unit Updated',
        'unit.deleted' => 'Unit Deleted',

        'record.archived' => 'Record Archived',
        'record.restored' => 'Record Restored',
        'lease.created' => 'Lease Created',
        'lease.updated' => 'Lease Updated',
        'lease.deleted' => 'Lease Deleted',

        'managing_organisation.created' => 'Managing Organisation Configured',

        'managing_organisation.updated' => 'Managing Organisation Updated',

        'payment.recorded' => 'Payment Recorded',

        'tenant_fund.classified' => 'Tenant Funds Classified',

        'rent_reserve.consumed' => 'Rent Reserve Consumed',

        'consumable_advance.consumed' => 'Consumable Advance Consumed',

        'security_deposit.deduction_recorded' => 'Security Deposit Deduction Recorded',

        'security_deposit.settled' => 'Security Deposit Settled',

        /* ---- V1.0.36 ---- */
        'support.message_sent' => 'Message Sent To Support',

        'owner_expense.recorded' => 'Owner Expense Recorded',

        'owner_deposit.recorded' => 'Owner Deposit Recorded',

        'owner_adjustment.recorded' => 'Owner Adjustment Recorded',

        'owner_payout.recorded' => 'Owner Payout Recorded',

        'invoice.downloaded' => 'Invoice Downloaded',

        'receipt.downloaded' => 'Receipt Downloaded',

        'owner_deposit_receipt.downloaded' => 'Owner Deposit Receipt Downloaded',

        'security_deposit_voucher.downloaded' => 'Security Deposit Voucher Downloaded',

        'invoice.resent' => 'Invoice Resent',

        'email.suppressed' => 'Email Withheld',

        'receipt.resent' => 'Receipt Resent',

        'report.exported' => 'Report Exported',

        'activity_log.exported' => 'Activity Log Exported',
    ],

    /*
    |--------------------------------------------------------------------------
    | Entity / Record Types
    |--------------------------------------------------------------------------
    */

    'entities' => [
        'user' => 'User',
        'party' => 'Party',
        'building' => 'Building',
        'unit' => 'Unit',
        'lease' => 'Lease',
        'payment' => 'Payment',
        'invoice' => 'Invoice',
        'receipt' => 'Receipt',
        'tenant_fund' => 'Tenant Fund',
        'rent_reserve' => 'Rent Reserve',
        'consumable_advance' => 'Consumable Advance',
        'security_deposit' => 'Security Deposit',
        'owner_expense' => 'Owner Expense',
        'owner_account' => 'Owner Account',
        'owner_transaction' => 'Owner Transaction',
        'owner_payout' => 'Owner Payout',
        'managing_organisation' => 'Managing Organisation',
        'report' => 'Report',
        'activity_log' => 'Activity Log',
    ],

    /*
    |--------------------------------------------------------------------------
    | Export Formats / Metadata
    |--------------------------------------------------------------------------
    */

    'formats' => [
        'pdf' => 'PDF',
        'csv' => 'CSV',
    ],

    'metadata_labels' => [
        'format' => 'Format',
        'report_type' => 'Report Type',
        'document_type' => 'Document Type',
        'delivery' => 'Delivery',
        'reference' => 'Reference',
        'invitation_sent' => 'Invitation Sent',
        'source' => 'Source',
    ],
];
