<?php

return [
    'common' => [
        'property_management' => 'Property Management',
        'dear' => 'Dear',
        'regards' => 'Regards',
        'generated_by' => 'This message was generated by Patrimoine.',
        'balance_due' => 'Balance Due',
        'due_date' => 'Due Date',
        'tenant' => 'Tenant',
    ],

    'invoice' => [
        'title' => 'Invoice :number',
        'subject' => 'Invoice :number - :organisation',
        'intro_before_number' => 'Please find attached your rent invoice',
        'intro_for' => 'for',
        'invoice_amount' => 'Invoice Amount',
        'amount_paid' => 'Amount Paid',
        'pdf_attached' => 'The full invoice is attached as a PDF.',
    ],

    'receipt' => [
        'title' => 'Payment Receipt',
        'subject' => 'Payment Receipt :number - :organisation',
        'confirm_before_property' => 'We confirm receipt of your payment for',
        'amount_received' => 'Amount Received',
        'receipt' => 'Receipt',
        'payment_date' => 'Payment Date',
        'payment_method' => 'Payment Method',
        'reference' => 'Reference',
        'pdf_attached' => 'Your official receipt is attached as a PDF.',
    ],

    'reminder' => [
        'title' => 'Rent Reminder',
        'subject' => 'Rent Reminder - Invoice :number - :organisation',
        'intro_before_number' => 'This is a reminder regarding rent invoice',
        'intro_for' => 'for',
        'overdue' => 'Our records indicate that this invoice is currently overdue.',
        'pay_by_due_date' => 'Please arrange payment by the due date.',
        'invoice_attached' => 'A copy of the invoice is attached for your reference.',
    ],

    'rent_increment' => [
        'title' => 'Notice of Rent Increment',
        'subject' => 'Notice of Rent Increment - :organisation',
        'intro_before_property' => 'This is to formally notify you that the monthly rent applicable to your tenancy',
        'at' => 'at',
        'intro_before_date' => 'is scheduled to change with effect from',
        'current_rent' => 'Current Monthly Rent',
        'increment' => 'Rent Increment',
        'new_rent' => 'New Monthly Rent',
        'effective_date' => 'Effective Date',
        'unchanged_until' => 'Your current rent will remain unchanged until the effective date stated above.',
        'contact_before' => 'Please contact',
        'contact_after' => 'if you require any clarification regarding this notice.',
    ],

    'owner_expense_bill' => [
        'title' => 'Owner Expense Bill',
        'subject' => 'Owner Expense Bill :number - :organisation',
        'intro' => 'Please find attached the itemized bill for expenses charged to your owner account.',
        'bill' => 'Bill',
        'bill_date' => 'Bill Date',
        'line_count' => 'Expense Lines',
        'total_billed' => 'Total Billed',
        'pdf_attached' => 'The full itemized bill is attached as a PDF.',
        'sent' => 'Owner expense bill email sent successfully.',
        'owner_email_missing' => 'Owner does not have an email address.',
    ],

    'payment_methods' => [
        'cash' => 'Cash',
        'bank_transfer' => 'Bank Transfer',
        'momo' => 'Mobile Payment',
        'mobile_money' => 'Mobile Payment',
        'cheque' => 'Cheque',
        'check' => 'Cheque',
    ],

    'user_invitation' => [
        'subject' => 'Set up your :organisation account',
        'title' => 'Set up your account',
        'greeting' => 'Hello :name,',
        'introduction' => 'You have been invited to use :organisation.',
        'action' => 'Set my password',
        'expiry' => 'This link expires in 24 hours.',
        'ignore' => 'If you were not expecting this invitation, you can ignore this email.',
    ],

    'password_reset' => [
        'subject' => 'Reset your :organisation password',
        'title' => 'Reset your password',
        'greeting' => 'Hello :name,',
        'introduction' => 'A password reset was requested for your :organisation account.',
        'action' => 'Reset my password',
        'expiry' => 'This link expires in 24 hours.',
        'ignore' => 'If you did not request this reset, you can ignore this email.',
    ],
    'transfer_voucher' => [
        'title' => 'Transfer Receipt',
        'subject' => 'Transfer Receipt :number - :organisation',
        'intro' => 'Please find attached the receipt for a transfer between funds we hold on your behalf.',
        'amount_moved' => 'Amount Moved',
        'voucher' => 'Receipt',
        'transfer_date' => 'Transfer Date',
        'from_fund' => 'From',
        'to_fund' => 'To',
        'reason' => 'Reason',
        'fund_rent_reserve' => 'Rent Reserve',
        'fund_consumable_advance' => 'Consumable Advance',
        'fund_security_deposit' => 'Security Deposit',
        'pdf_attached' => 'Your official transfer receipt is attached as a PDF.',
    ],

    'owner_reserve_transfer' => [
        'title' => 'Owner Account Transfer',
        'subject' => 'Account Transfer Voucher :number - :organisation',
        'intro' => 'Please find attached the voucher for a transfer between your accounts held with us.',
        'amount_moved' => 'Amount Moved',
        'voucher' => 'Voucher',
        'transfer_date' => 'Transfer Date',
        'from_account' => 'From',
        'to_account' => 'To',
        'payout_account' => 'Payout Account (from rent)',
        'deposit_account' => 'Deposit / Expense Account',
        'reason' => 'Reason',
        'pdf_attached' => 'Your official transfer voucher is attached as a PDF.',
    ],

    'tenant_fund_expense' => [
        'title' => 'Tenant Expense Voucher',
        'subject' => 'Tenant Expense Voucher :number - :organisation',
        'intro' => 'Please find attached the voucher for an expense settled from funds we hold on your behalf.',
        'amount_moved' => 'Amount',
        'voucher' => 'Voucher',
        'transfer_date' => 'Date',
        'source_fund' => 'Source Fund',
        'description' => 'Description',
        'fund_rent_reserve' => 'Rent Reserve',
        'fund_consumable_advance' => 'Consumable Advance',
        'fund_security_deposit' => 'Security Deposit',
        'pdf_attached' => 'Your official expense voucher is attached as a PDF.',
    ],

    /*
    |----------------------------------------------------------------------
    | V1.0.10 shared email layout
    |----------------------------------------------------------------------
    */
    'layout' => [
        'on_behalf_of' => 'Sent on behalf of :organisation',
        'sent_by_product' => 'This message was sent by Patrimoine 365.',
        'operated_by' => 'is operated by',
        'questions' => 'Questions?',
    ],

    'email_verification' => [
        'subject' => 'Verify your email address — Patrimoine 365',
        'title' => 'Verify your email address',
        'preheader' => 'One click and your Patrimoine 365 organisation is ready.',
        'heading' => 'Verify your email address',
        'greeting' => 'Hello :name,',
        'introduction' => 'Welcome to Patrimoine 365! Your organisation ":organisation" has been created. Confirm your email address to activate your account and sign in.',
        'action' => 'Verify email address',
        'expiry' => 'This link is valid for 48 hours.',
        'ignore' => 'If you did not create this account, you can safely ignore this email — nothing will be activated without this verification.',
    ],

    'mfa_code' => [
        'subject' => ':code is your Patrimoine 365 sign-in code',
        'title' => 'Your sign-in code',
        'preheader' => 'Use this code to finish signing in.',
        'heading' => 'Your sign-in code',
        'greeting' => 'Hello :name,',
        'introduction' => 'Use the code below to finish signing in to Patrimoine 365:',
        'expiry' => 'This code expires in :minutes minutes and can only be used once.',
        'ignore' => 'If you did not try to sign in, we recommend changing your password immediately.',
    ],

    'plans' => [
        'free' => 'Free',
        'standard' => 'Standard',
        'professional' => 'Professional',
    ],

    'license_issued' => [
        'subject' => 'Your Patrimoine 365 plan: :plan',
        'title' => 'Your plan has been updated',
        'preheader' => 'Your organisation is now on the :plan plan.',
        'heading' => 'Your plan has been updated',
        'greeting' => 'Hello :name,',
        'introduction' => 'A new licence has been activated for ":organisation". Here is what now applies:',
        'plan' => 'Plan',
        'starts_on' => 'Starts',
        'expires_on' => 'Valid until',
        'no_expiry' => 'No expiry',
        'questions' => 'Questions about your plan or invoice?',
    ],

    'plan_expiry' => [
        'subject' => 'Your Patrimoine 365 plan ends in :days day(s)',
        'title' => 'Your plan is ending soon',
        'heading' => 'Your plan ends in :days day(s)',
        'greeting' => 'Hello :name,',
        'introduction_trial' => 'The Professional trial for ":organisation" ends on :date.',
        'introduction_license' => 'The :plan licence for ":organisation" ends on :date.',
        'what_changes' => 'Afterwards your organisation continues on the Free plan: all of your data stays exactly as it is, but reports, exports and automated reminders pause, and the Free plan limits apply to creating new records.',
        'renew' => 'To renew or change plans, contact',
    ],
];
