<?php

return [
    'common' => [
        'property_management' => 'Property Management',
        'dear' => 'Dear',
        'regards' => 'Regards',
        'generated_by' => 'This message was generated by Patrimoine.',
        'balance_due' => 'Balance Due',
        'due_date' => 'Due Date',
        'tenant' => 'Tenant',
    ],

    'invoice' => [
        'title' => 'Invoice :number',
        'subject' => 'Invoice :number - :organisation',
        'intro_before_number' => 'Please find attached your rent invoice',
        'intro_for' => 'for',
        'invoice_amount' => 'Invoice Amount',
        'amount_paid' => 'Amount Paid',
        'pdf_attached' => 'The full invoice is attached as a PDF.',
    ],

    'receipt' => [
        'title' => 'Payment Receipt',
        'subject' => 'Payment Receipt :number - :organisation',
        'confirm_before_property' => 'We confirm receipt of your payment for',
        'amount_received' => 'Amount Received',
        'receipt' => 'Receipt',
        'payment_date' => 'Payment Date',
        'payment_method' => 'Payment Method',
        'reference' => 'Reference',
        'pdf_attached' => 'Your official receipt is attached as a PDF.',
    ],

    'reminder' => [
        'title' => 'Rent Reminder',
        'subject' => 'Rent Reminder - Invoice :number - :organisation',
        'intro_before_number' => 'This is a reminder regarding rent invoice',
        'intro_for' => 'for',
        'overdue' => 'Our records indicate that this invoice is currently overdue.',
        'pay_by_due_date' => 'Please arrange payment by the due date.',
        'invoice_attached' => 'A copy of the invoice is attached for your reference.',
    ],

    'rent_increment' => [
        'title' => 'Notice of Rent Increment',
        'subject' => 'Notice of Rent Increment - :organisation',
        'intro_before_property' => 'This is to formally notify you that the monthly rent applicable to your tenancy',
        'at' => 'at',
        'intro_before_date' => 'is scheduled to change with effect from',
        'current_rent' => 'Current Monthly Rent',
        'increment' => 'Rent Increment',
        'new_rent' => 'New Monthly Rent',
        'effective_date' => 'Effective Date',
        'unchanged_until' => 'Your current rent will remain unchanged until the effective date stated above.',
        'contact_before' => 'Please contact',
        'contact_after' => 'if you require any clarification regarding this notice.',
    ],

    'payment_methods' => [
        'cash' => 'Cash',
        'bank_transfer' => 'Bank Transfer',
        'momo' => 'MoMo',
        'mobile_money' => 'Mobile Money',
        'cheque' => 'Cheque',
        'check' => 'Cheque',
    ],

    'user_invitation' => [
        'subject' => 'Set up your :organisation account',
        'title' => 'Set up your account',
        'greeting' => 'Hello :name,',
        'introduction' => 'You have been invited to use :organisation.',
        'action' => 'Set my password',
        'expiry' => 'This link expires in 24 hours.',
        'ignore' => 'If you were not expecting this invitation, you can ignore this email.',
    ],



    'password_reset' => [
        'subject' =>
            'Reset your :organisation password',
        'title' =>
            'Reset your password',
        'greeting' =>
            'Hello :name,',
        'introduction' =>
            'A password reset was requested for your :organisation account.',
        'action' =>
            'Reset my password',
        'expiry' =>
            'This link expires in 24 hours.',
        'ignore' =>
            'If you did not request this reset, you can ignore this email.',
    ],
];
