<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

/**
 * Validate final settlement of a Lease's Security Deposit.
 *
 * Voucher numbers are generated by Patrimoine and therefore are not accepted
 * as user input.
 */
class SettleSecurityDepositRequest extends FormRequest
{
    /**
     * Authorization is enforced by the authenticated Property Manager routes.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * @return array<string, mixed>
     */
    public function rules(): array
    {
        return [
            'settlement_date' => [
                'required',
                'date',
            ],

            'notes' => [
                'nullable',
                'string',
            ],
        ];
    }
}
