<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

/**
 * Validate final settlement of a Lease's Security Deposit.
 *
 * Voucher numbers are generated by Patrimoine and therefore are not accepted
 * as user input.
 */
class SettleSecurityDepositRequest extends FormRequest
{
    /**
     * Authorization is enforced by the authenticated Property Manager routes.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * @return array<string, mixed>
     */
    public function rules(): array
    {
        return [
            'settlement_date' => [
                'required',
                'date',
            ],

            /*
             * The authoritative refund amount is calculated by
             * SecurityDepositService.
             *
             * The channel is therefore request-level optional. After the
             * accounting cutover, the service requires it only when the
             * settlement genuinely produces an outgoing refund.
             */
            'refund_payment_method' => [
                'nullable',
                'string',
                'in:cash,bank_transfer,momo,cheque',
            ],

            'notes' => [
                'nullable',
                'string',
            ],
        ];
    }
}
