<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>{{ $title }}</title>

    <style>
        @page {
            margin: 36px 42px;
        }

        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 10px;
            color: #222222;
            line-height: 1.4;
        }

        .header {
            margin-bottom: 24px;
            border-bottom: 2px solid #222222;
            padding-bottom: 12px;
        }

        .brand {
            font-size: 22px;
            font-weight: bold;
        }

        .subtitle {
            margin-top: 2px;
            color: #666666;
            font-size: 9px;
        }

        .report-title {
            margin-top: 14px;
            font-size: 17px;
            font-weight: bold;
        }

        .section {
            margin-top: 20px;
            page-break-inside: avoid;
        }

        .section-title {
            font-size: 12px;
            font-weight: bold;
            margin-bottom: 6px;
            padding-bottom: 4px;
            border-bottom: 1px solid #cccccc;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th {
            background: #f1f1f1;
            text-align: left;
            font-weight: bold;
            padding: 6px;
            border: 1px solid #dddddd;
        }

        td {
            padding: 6px;
            vertical-align: top;
            border: 1px solid #dddddd;
        }

        .label {
            width: 38%;
            font-weight: bold;
            background: #fafafa;
        }

        .empty {
            color: #888888;
            font-style: italic;
            padding: 8px 0;
        }

        .footer {
            margin-top: 30px;
            border-top: 1px solid #dddddd;
            padding-top: 8px;
            color: #888888;
            font-size: 8px;
        }
    </style>
</head>

<body>
    <div class="header">
        <div class="brand">
            Patrimoine
        </div>

        <div class="subtitle">
            Property Management
        </div>

        <div class="report-title">
            {{ $title }}
        </div>
    </div>

    @foreach($sections as $section)
        <div class="section">
            <div class="section-title">
                {{ $section['title'] }}
            </div>

            @if($section['type'] === 'pairs')
                @if(count($section['rows']) === 0)
                    <div class="empty">
                        No information available.
                    </div>
                @else
                    <table>
                        @foreach($section['rows'] as $row)
                            <tr>
                                <td class="label">
                                    {{ $row['label'] }}
                                </td>

                                <td>
                                    {{ $row['value'] }}
                                </td>
                            </tr>
                        @endforeach
                    </table>
                @endif
            @endif

            @if($section['type'] === 'table')
                @if(count($section['rows']) === 0)
                    <div class="empty">
                        No records for this section.
                    </div>
                @else
                    <table>
                        <thead>
                            <tr>
                                @foreach($section['headers'] as $header)
                                    <th>
                                        {{ $header }}
                                    </th>
                                @endforeach
                            </tr>
                        </thead>

                        <tbody>
                            @foreach($section['rows'] as $row)
                                <tr>
                                    @foreach($row as $value)
                                        <td>
                                            {{ $value }}
                                        </td>
                                    @endforeach
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                @endif
            @endif
        </div>
    @endforeach

    <div class="footer">
        Generated by Patrimoine.
    </div>
</body>
</html>
