<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Create the invoices table.
 *
 * An Invoice represents an amount contractually due from a tenant
 * under a Lease. Payments and payment allocations are intentionally
 * stored separately so Patrimoine can support partial payments,
 * overpayments and FIFO settlement of old debt.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('invoices', function (Blueprint $table) {
            $table->id();

            /*
             * Every invoice belongs to exactly one Lease.
             *
             * Lease deletion is restricted because issued invoices are
             * part of the financial audit trail and should not disappear
             * simply because a lease record is removed.
             */
            $table->foreignId('lease_id')
                ->constrained()
                ->restrictOnDelete();

            /*
             * Human-readable invoice reference.
             *
             * Example:
             * INV-2026-000001
             *
             * The actual numbering strategy will be implemented in the
             * invoice service rather than generated by the database.
             */
            $table->string('invoice_number')->unique();

            /*
             * Billing period covered by this invoice.
             *
             * Keeping explicit period dates makes reporting and
             * reconciliation easier for monthly, quarterly, bi-yearly
             * and yearly leases.
             */
            $table->date('period_start');
            $table->date('period_end');

            /*
             * Date on which the invoice was issued and date by which
             * payment is contractually expected.
             */
            $table->date('issue_date');
            $table->date('due_date');

            /*
             * Invoice lifecycle.
             *
             * draft     = generated but not yet formally issued
             * issued    = outstanding invoice
             * partial   = some amount has been allocated
             * paid      = fully settled
             * cancelled = cancelled without deleting the audit record
             */
            $table->enum('status', [
                'draft',
                'issued',
                'partial',
                'paid',
                'cancelled',
            ])->default('draft');

            /*
             * VAT-inclusive invoice total.
             *
             * Patrimoine stores monetary values as whole currency units.
             */
            $table->unsignedBigInteger('total_amount');

            /*
             * VAT rate copied from the Lease when the invoice is created.
             *
             * This snapshot is important because changing the Lease VAT
             * later must not rewrite historical invoices.
             */
            $table->decimal('vat_rate', 5, 2);

            /*
             * Explicit VAT-inclusive basis details retained for historical
             * reporting. All three values remain integer currency amounts.
             */
            $table->unsignedBigInteger('net_amount');
            $table->unsignedBigInteger('vat_amount');

            /*
             * Optional proration amount included in this invoice.
             *
             * NULL means no separate proration component applies.
             * Zero remains a valid explicit amount.
             */
            $table->unsignedBigInteger('proration_amount')->nullable();

            /*
             * Free-form note for exceptional billing circumstances,
             * adjustments or administrative explanation.
             */
            $table->text('notes')->nullable();

            $table->timestamps();

            /*
             * Common reporting and FIFO allocation lookup paths.
             */
            $table->index(['lease_id', 'status']);
            $table->index(['lease_id', 'due_date']);
            $table->index('issue_date');
            $table->index('due_date');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('invoices');
    }
};
